/* -------------------------------------------
   PRESENT SIMPLE – AFFIRMATIVE (60)
------------------------------------------- */
const PS_aff = [
  "She usually walks to school.",
  "He plays the guitar every afternoon.",
  "They enjoy quiet mornings together.",
  "My cat sleeps on my backpack.",
  "I like how this coffee smells.",
  "We live near the park.",
  "The dog understands simple commands.",
  "My brother cooks dinner on Fridays.",
  "She reads before going to bed.",
  "He often forgets his keys at home.",
  "They play football in the playground.",
  "The shop opens at nine.",
  "My sister studies French at school.",
  "He likes drawing robots.",
  "We eat lunch together on weekends.",
  "The train leaves at eight.",
  "She loves rainy days.",
  "They walk their dog every evening.",
  "He drinks tea in the morning.",
  "My parents cook dinner together.",
  "The sun rises in the east.",
  "Birds fly in the sky.",
  "She enjoys quiet music.",
  "He plays chess with his dad.",
  "We visit our grandparents on Sundays.",
  "They clean their room every Saturday.",
  "My cousin lives in Madrid.",
  "She likes chocolate ice cream.",
  "He reads comics after school.",
  "We watch movies on Fridays.",
  "They help their neighbours sometimes.",
  "My dog waits for me at the door.",
  "She sings in the school choir.",
  "He practices basketball every day.",
  "We talk during lunch break.",
  "They share snacks in class.",
  "My aunt teaches English.",
  "She paints beautiful pictures.",
  "He listens to rock music.",
  "We enjoy sunny afternoons.",
  "They laugh a lot together.",
  "My friend plays the piano.",
  "She writes stories in her notebook.",
  "He collects stickers.",
  "We celebrate birthdays at home.",
  "They travel during holidays.",
  "My grandma bakes amazing cakes.",
  "She waters the plants every morning.",
  "He feeds the cat before school.",
  "We take the bus to class.",
  "They study in the library.",
  "My uncle works in a hospital.",
  "She keeps her room tidy.",
  "He plays video games after homework.",
  "We read books in English class.",
  "They enjoy long walks.",
  "My neighbour grows tomatoes.",
  "She practices yoga on weekends.",
  "He likes science experiments."
];


/* -------------------------------------------
   PRESENT SIMPLE – NEGATIVE (60)
------------------------------------------- */
const PS_neg = [
  "She doesn’t like cold pizza.",
  "They don’t study on Sundays.",
  "He does not enjoy long movies.",
  "I don’t drink soda anymore.",
  "The cat doesn’t sleep in its bed.",
  "We don’t walk to school when it rains.",
  "She does not play video games.",
  "They don’t eat meat.",
  "He doesn’t listen to loud music.",
  "I do not watch TV in the morning.",
  "She doesn’t enjoy crowded places.",
  "They don’t visit the museum often.",
  "He does not like spicy food.",
  "We don’t clean the house on Fridays.",
  "My dog doesn’t bark at night.",
  "She doesn’t drink coffee.",
  "He doesn’t wake up early.",
  "They don’t play tennis.",
  "We don’t buy snacks at school.",
  "My brother doesn’t study French.",
  "She does not like horror movies.",
  "He doesn’t eat vegetables.",
  "They don’t walk their dog every day.",
  "We don’t travel in winter.",
  "My parents don’t watch reality shows.",
  "She doesn’t read newspapers.",
  "He does not enjoy swimming.",
  "They don’t help with chores sometimes.",
  "We don’t use our phones in class.",
  "My cousin doesn’t live nearby.",
  "She doesn’t like loud noises.",
  "He doesn’t play the violin.",
  "They don’t drink tea.",
  "We don’t stay up late.",
  "My aunt doesn’t teach maths.",
  "She doesn’t paint landscapes.",
  "He does not listen to jazz.",
  "They don’t laugh at bad jokes.",
  "We don’t celebrate Halloween.",
  "My friend doesn’t play football.",
  "She doesn’t write poems.",
  "He doesn’t collect stamps.",
  "They don’t travel by train.",
  "We don’t bake cakes at home.",
  "My grandma doesn’t use a smartphone.",
  "She doesn’t water the plants daily.",
  "He doesn’t feed the dog in the morning.",
  "They don’t study in the afternoon.",
  "We don’t take the metro.",
  "My uncle doesn’t work on weekends.",
  "She doesn’t keep old photos.",
  "He doesn’t play board games.",
  "They don’t enjoy long walks.",
  "We don’t read magazines.",
  "My neighbour doesn’t grow flowers.",
  "She doesn’t practice yoga.",
  "He doesn’t like science fiction.",
  "They don’t eat breakfast early.",
  "We don’t talk during exams."
];
